#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.trade.com:
    container_name: orderer.trade.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer.trade.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer.trade.com/tls/:/var/hyperledger/orderer/tls
    - orderer.trade.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.hosp1org.trade.com:
    container_name: peer0.hosp1org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hosp1org.trade.com
      - CORE_PEER_ADDRESS=peer0.hosp1org.trade.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hosp1org.trade.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hosp1org.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hosp1org.trade.com:7051
      - CORE_PEER_LOCALMSPID=Hosp1OrgMSP
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/hosp1org.trade.com/peers/peer0.hosp1org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hosp1org.trade.com/peers/peer0.hosp1org.trade.com/tls:/etc/hyperledger/fabric/tls
        - ./peer0.hosp1org.trade.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.hosp2org.trade.com:
    container_name: peer0.hosp2org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hosp2org.trade.com
      - CORE_PEER_ADDRESS=peer0.hosp2org.trade.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hosp2org.trade.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hosp2org.trade.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hosp2org.trade.com:8051
      - CORE_PEER_LOCALMSPID=Hosp2OrgMSP
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/hosp2org.trade.com/peers/peer0.hosp2org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hosp2org.trade.com/peers/peer0.hosp2org.trade.com/tls:/etc/hyperledger/fabric/tls
        - ./peer0.hosp2org.trade.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer1.hosp1org.trade.com:
    container_name: peer1.hosp1org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hosp1org.trade.com
      - CORE_PEER_ADDRESS=peer1.hosp1org.trade.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hosp1org.trade.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hosp1org.trade.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hosp1org.trade.com:9051
      - CORE_PEER_LOCALMSPID=Hosp1OrgMSP
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/hosp1org.trade.com/peers/peer1.hosp1org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hosp1org.trade.com/peers/peer1.hosp1org.trade.com/tls:/etc/hyperledger/fabric/tls
        - ./peer1.hosp1org.trade.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.hosp2org.trade.com:
    container_name: peer1.hosp2org.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hosp2org.trade.com
      - CORE_PEER_ADDRESS=peer1.hosp2org.trade.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hosp2org.trade.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hosp2org.trade.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hosp2org.trade.com:10051
      - CORE_PEER_LOCALMSPID=Hosp2OrgMSP
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/hosp2org.trade.com/peers/peer1.hosp2org.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hosp2org.trade.com/peers/peer1.hosp2org.trade.com/tls:/etc/hyperledger/fabric/tls
        - ./peer0.hosp2org.trade.com:/var/hyperledger/production
    ports:
      - 10051:10051

