#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.trade.com:
  peer0.hosp1org.trade.com:
  peer0.hosp2org.trade.com:
  ca.hosp1org.trade.com:
  ca.hosp2org.trade.com:


networks:
  trade:
services:
  hosp1-ca:
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    platform: $PLATFORM
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hosp1org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hosp1org.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hosp1org.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hosp1org.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ca.hosp1org.trade.com:/etc/hyperledger/fabric-ca-server
    container_name: ca.hosp1org.trade.com
    networks:
      - trade

  hosp2-ca:
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    platform: $PLATFORM
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hosp2org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hosp2org.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --port 8054 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hosp2org.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hosp2org.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ca.hosp2org.trade.com:/etc/hyperledger/fabric-ca-server
    container_name: ca.hosp2org.trade.com
    networks:
      - trade


  orderer.trade.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.trade.com
    container_name: orderer.trade.com
    networks:
      - trade

  peer0.hosp1org.trade.com:
    container_name: peer0.hosp1org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hosp1org.trade.com
    networks:
      - trade

  peer0.hosp2org.trade.com:
    container_name: peer0.hosp2org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hosp2org.trade.com
    networks:
      - trade

  peer1.hosp1org.trade.com:
    container_name: peer1.hosp1org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hosp1org.trade.com
    networks:
      - trade

  peer1.hosp2org.trade.com:
    container_name: peer1.hosp2org.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hosp2org.trade.com
    networks:
      - trade

